/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./assets/styles/**/*.scss",
    "./templates/**/*.html.twig",
    "./assets/js/**/*.js",
    "./assets/js/**/*.jsx",
    "./node_modules/flowbite/dist/**/*.js",
    "./node_modules/tw-elements/dist/js/**/*.js",
  ],
  theme: {
    extend: {
      fontFamily: {
        poppins: ["Poppins", "sans-serif"],
        samarkan: ["Samarkan", "sans-serif"],
        playfair: ["PlayfairDisplay", "sans-serif"],
        opensans: ["OpenSans", "sans-serif"],
      },
      colors: {
        transparent: "transparent",
        current: "currentColor",
        white: "#ffffff",
        primary: "#cda45e",
        primary: {
          100: "#ecbc6b",
          200: "#dfb265",
          300: "#daae63",
          400: "#d0a65f",
          500: "#cda45e",
          600: "#be9857",
          700: "#b49052",
          800: "#ae8c4f",
          900: "#9f8048",
        },
        secondary: "#0c0b09",
        secondary: {
          100: "#ae9d85",
          200: "#9a8b75",
          300: "#867966",
          400: "#716656",
          500: "#5f5648",
          600: "#4b4439",
          700: "#37322a",
          800: "#221f1a",
          900: "#0c0b09",
        },
        tetriary: "#1a1814",
        success: "#00500a",
        info: "#1d1d2e",
        warning: "#ffa600",
        danger: "#a40010",
        first: "#cda45e",
        second: "#0c0b09",
        third: "#1a1814",
        light: "#ffe4e6",
      },
      safelist: [
        "animate-[fade-in_1s_ease-in-out]",
        "animate-[fade-out_1s_ease-in-out]",
      ],
    },
  },
  plugins: [require("tw-elements/dist/plugin"), require("flowbite/plugin")],
};
